stages:
  prepare:
    cmd: python -m mates.modeling.prepare.py
    deps:
    - data/raw/labels.csv
    - data/raw/test
    - data/raw/train
    - mates/modeling/prepare.py
    params:
    - prepare.is_train
    - prepare.save_processed
    - prepare.seed
    - prepare.split_size
    outs:
    - data/processed/output_shape.pkl
    - data/processed/train_data.pkl
    - data/processed/valid_data.pkl
  train:
    cmd: python -m mates.modeling.train.py
    deps:
    - data/processed/output_shape.pkl
    - data/processed/train_data.pkl
    - data/processed/valid_data.pkl
    - mates/modeling/train.py
    params:
    - train.save_model
    - train.epochs
    - train.batch_size
    - train.experiment_name
    - train.model_name
    - train.model_url
    outs:
    - data/models/
