prepare:
  is_train: True
  save_processed: True
  seed: 42
  split_size: 0.3
  batch_size: 62
train:
  save_model: True
  experiment_name: "hyperparameters"
  model_name: "mobilenet"
  model_url: "https://www.kaggle.com/models/google/mobilenet-v2/TensorFlow2/130-224-feature-vector/2"
  hyperparams:
    epochs: [6]
    batch_size: [32, 62]
    optimizer: [adamw, adam, sgd, rmsprop]
  patience: [5]
  metrics: ["accuracy"]
  monitor: "accuracy"
predict:
  model_name: "mobilenet_exp_batch_32"
  batch_size: 32