prepare:
  is_train: True
  save_processed: True
  seed: 42
  split_size: 0.3
train:
  save_model: True
  epochs: 20
  batch_size: 32
  experiment_name: "xxx"
  model_name: "xxx"
  model_url: "https://kaggle.com/models/google/mobilenet-v2/TensorFlow2/035-128-classification/1
  batch_size: 32