prepare:
  is_train: True
  save_processed: True
  seed: 42
  split_size: 0.3
  batch_size: 32
train:
  save_model: True
  epochs: 15
  batch_size: 32
  experiment_name: "batch_32_rmsprop"
  model_name: "mobilenet"
  model_url: "https://kaggle.com/models/google/mobilenet-v2/TensorFlow2/035-128-classification/1"
  optimizer: rmsprop
  metrics: ["accuracy"]
  monitor: "val_accuracy"
  patience: 5
