name: Test

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        
      - name: Setup a local virtual environment (if no poetry.toml file)
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local
          
      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
          
      - name: Install the project dependencies
        run: poetry install
      
      - name: Download files tracked by DVC
        run: poetry run dvc pull
      
      - name: Run pytest
        run: poetry run pytest